apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: shared-apps

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - shared

      containers:
        - name: backend

          image: tanishkaborade/feedback-backend:v2

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: MYSQL_HOST
              value: "mysql-service.critical-apps.svc.cluster.local"

            - name: MYSQL_USER
              value: "root"

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret-shared-apps
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: "companydb"

          startupProbe:
            exec:
              command:
                - sh
                - -c
                - >
                  python3 -c "import os,mysql.connector; mysql.connector.connect(host=os.environ['MYSQL_HOST'], user=os.environ['MYSQL_USER'], password=os.environ['MYSQL_PASSWORD'], connection_timeout=3).close()"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 3

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "200m"