
apiVersion: v1
kind: ResourceQuota
metadata:
  name: critical-apps-quota
  namespace: critical-apps
spec:
  hard:
    pods: "10"
    services: "10"
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: critical-apps-limits
  namespace: critical-apps
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      default:
        cpu: 200m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 64Mi
      max:
        cpu: "1"
        memory: "1Gi"
