
apiVersion: v1
kind: ResourceQuota
metadata:
  name: shared-apps-quota
  namespace: shared-apps
spec:
  hard:
    pods: "10"
    services: "10"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: shared-apps-limits
  namespace: shared-apps
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 100m
        memory: 128Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: "500m"
        memory: 512Mi
