apiVersion: v1
kind: Pod
metadata:
  name: critical-test-pod
  namespace: critical-apps

spec:
  tolerations:
    - key: "critical"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - critical

  containers:
    - name: nginx
      image: nginx