apiVersion: v1
kind: Pod
metadata:
  name: shared-test-pod
  namespace: shared-apps

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - shared

  containers:
    - name: nginx
      image: nginx